// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eazqnpaykmvtnowrqwtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhenFucGF5a212dG5vd3Jxd3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTQwNDAsImV4cCI6MjA2OTg3MDA0MH0.wCJ-O4hFmDdha4BbSU94VfXNCrZd9O1XcB4AopRxdaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});